;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-indent-line-or-region
        counsel-M-x
        end-of-visual-line
        lps/eval-and-replace-last-sexp
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        ))
