;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-environment
        LaTeX-insert-left-brace
        TeX-font
        beginning-of-visual-line
        c-indent-line-or-region
        counsel-M-x
        end-of-visual-line
        forward-sentence
        hungry-delete-backward
        hungry-delete-forward
        lps/eval-and-replace-last-sexp
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        paredit-forward-delete
        paredit-forward-kill-word
        reftex-label
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-words-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        hydra-multiple-cursors/mc/mark-all-dwim
        hydra-multiple-cursors/nil
        swiper-mc
        consult-line
        ))
