;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc/mark-all-dwim
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        ))
